cbvcrud/urls.py
from django.contrib import admin
from django.urls import path
from cbvcrudapp import views
from django.views.generic.base import TemplateView
  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.greetingview.as_view(greetingmsg='')),
    path('slv/',views.studentlistview.as_view(template_name='studentlist.html'),name='list'),
    path('<int:pk>/',views.studentdetailview.as_view(template_name='studentdetail.html'),name='detail'),
    path('create/',views.studentcreate.as_view(template_name='forms.html')),
    path('update/<int:pk>/',views.studentupdate.as_view(template_name='forms.html')),
    path('delete/<int:pk>/',views.studentdelete.as_view(template_name='delete.html')),
    path('',TemplateView.as_view(template_name="studentlist.html"),name="intro")
]
    
    

cbvcrudapp/models.py
from django.db import models
from django.urls import reverse 

# Create your models here.

class student(models.Model):
   # id = models.IntegerField()
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    testscore1 = models.FloatField(default=0)
    testscore2= models.FloatField(default=0)
    testscore3 = models.FloatField(default=0)
    testscore4 = models.FloatField(default=0)
    testscore5 = models.FloatField(default=0)
    testscore6 = models.FloatField(default=0)
    
    
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={"pk": self.pk})
    

cbvcrudapp/views.py
from django.shortcuts import render
from django.views.generic import View,ListView,DetailView,CreateView,DeleteView,UpdateView
from cbvcrudapp.models import student
from django.urls import reverse_lazy
from django.http import HttpResponse

# Create your views here.
class greetingview(View):
    greetingmsg= "Hello here idk!!"
    def get(self,request):
        return HttpResponse(self.greetingmsg)
class studentlistview(ListView):
    model = student
   # def get(self,request):
        
       # return render(request,'studentlist.html',{'student':student})
    #default template_name is studentlist.html
    #default context_object_name is studentlist
class studentdetailview(DetailView):
    model = student
    #default template_name is student_detail.html
    #default context_object_name is studentdetail.detail
    
class studentcreate(CreateView):
    model = student
    fields = ('firstname','lastname','testscore1','testscore2','testscore3','testscore4','testscore5','testscore6')    
class studentupdate(UpdateView):
    model = student  
    fields=('firstname','lastname','testscore1','testscore2','testscore3','testscore4','testscore5','testscore6',) 
     
    
class studentdelete(DeleteView):
    model = student
    success_url = reverse_lazy('list')
    
      
  

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block body_block %}
        {% endblock %}
        

    </body>
</html>

templates/delete.html
<!DOCTYPE html>
{% extends "./base.html"%}
{%block body_block%}
        <h1>details after deleted</h1>
       <table>
        <tr>
            <td>{{student.firstname}} ?</td>
            
            <form method="POST" >
                {% csrf_token %}
                <input type="submit" value="confirm">
                <a href ="/{{student.id}}">Cancel</a>

            </form>
        </tr>
       </table>
   {%endblock%}

templates/forms.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Create Student details</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Create students</h1>
        <form method="post">
         {{form.as_p}}
         {% csrf_token%}
         <input type="submit" value="Save">
        </form>
        
        
        
        <script src="" async defer></script>
    </body>
</html>

templates/studentdetail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Student detail</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <ol>
            
            <h3><li>First name: {{student.firstname}}</li></h3>
            <h3><li>Last name: {{student.lastname}}</li></h3>
            <h3><li>Test Score1: {{student.testscore1}}</li></h3>
            <h3><li>Test Score2: {{student.testscore2}}</li></h3>
            <h3><li>Test Score3: {{student.testscore3}}</li></h3>
            <h3><li>Test Score4: {{student.testscore4}}</li></h3>
            <h3><li>Test Score5: {{student.testscore5}}</li></h3>
            <h3><li>Test Score6: {{student.testscore6}}</li></h3>

            <td><a href="/delete/{{student.id}}">Delete</a></td>
            <td><a href="/update/{{student.id}}">Update</a></td>
        </ol>
        <a href ="/slv">back</a>
        
        <script src="" async defer></script>
    </body>
</html>

templates/studentlist.html
<!DOCTYPE html>
{% block ody_block%}

<html lang ="en">
    <head>
        <meta charset = "utf-8">
        <title> Students mark list </title>

    </head>
    <body>
        <a href = "/create">Create data</a><br/>
       <h1>Students :</h1>
       <table border=2 >
        <thead>
            <th>Id</th>
            <th>Firstname</th>
            <th>Lastname</th>
            
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>

            
        </thead>
        {% for i in student_list %}
        <tr>
            <td><a href="/{{i.id}}">{{i.id}}</a></td>
            <td>{{i.firstname |lower}}</td>
            <td>{{i.lastname }}</td>
            <td>{{i.testscore1 | add:"2"}}</td>
            <td>{{i.testscore2}}</td>
            <td>{{i.testscore3}}</td>
            <td>{{i.testscore4}}</td>
            <td>{{i.testscore5}}</td>
            <td>{{i.testscore6}}</td>
            {% regroup student_list|dictsort:"firstname" by firstname as name %}
            {% empty %}
            <li>Sorry, no data in this list.</li>
            

        


        </tr>
        {% endfor %}
       </table>
    </body>

{%endblock%}
    </html>